# Generated by Django 5.2.8 on 2025-11-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymate_app', '0004_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/default.jpg', upload_to='profile_pics/'),
        ),
    ]
